name: Issues

on:
  issues:
    types: [opened, labeled]

permissions:
  # for auto hash fixing
  contents: write
  issues: write

jobs:
  issueHandler:
    name: IssueHandler
    runs-on: windows-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: IssueHandler
        uses: ScoopInstaller/GithubActions@main
        if: github.event.action == 'opened' || (github.event.action == 'labeled' && contains(github.event.issue.labels.*.name, 'verify'))
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
